//! Compile-only C/C++ contracts for every public repr(C) structure.
use std::fmt::Write;
use syscalls::*;

#[test]
fn export_layout_contract() {
    let mut header =
        String::from("/* Rust layout contract; generated by tests/layout_contract.rs. */\n");
    macro_rules! layout {
        ($ty:ident; $($field:ident),+ $(,)?) => {{
            writeln!(header, "ASSERT(sizeof(X_{}) == {}, \"{} size\");", stringify!($ty), size_of::<$ty>(), stringify!($ty)).unwrap();
            writeln!(header, "ASSERT(ALIGNOF(X_{}) == {}, \"{} alignment\");", stringify!($ty), align_of::<$ty>(), stringify!($ty)).unwrap();
            $(writeln!(header, "ASSERT(offsetof(X_{}, {}) == {}, \"{}.{} offset\");", stringify!($ty), stringify!($field), core::mem::offset_of!($ty, $field), stringify!($ty), stringify!($field)).unwrap();)+
        }};
    }
    layout!(UNICODE_STRING; Length, MaximumLength, Buffer);
    layout!(OBJECT_ATTRIBUTES; Length, RootDirectory, ObjectName, Attributes, SecurityDescriptor, SecurityQualityOfService);
    layout!(IO_STATUS_BLOCK; Status, Information);
    layout!(CLIENT_ID; UniqueProcess, UniqueThread);
    layout!(LARGE_INTEGER_PARTS; LowPart, HighPart);
    layout!(GENERIC_MAPPING; GenericRead, GenericWrite, GenericExecute, GenericAll);
    layout!(LUID; LowPart, HighPart);
    layout!(LUID_AND_ATTRIBUTES; Luid, Attributes);
    layout!(PRIVILEGE_SET; PrivilegeCount, Control, Privilege);
    layout!(TOKEN_PRIVILEGES; PrivilegeCount, Privileges);
    layout!(SID_AND_ATTRIBUTES; Sid, Attributes);
    layout!(TOKEN_GROUPS; GroupCount, Groups);
    layout!(SECURITY_QUALITY_OF_SERVICE; Length, ImpersonationLevel, ContextTrackingMode, EffectiveOnly);
    layout!(INITIAL_TEB; OldStackBase, OldStackLimit, StackBase, StackLimit, StackAllocationBase);
    layout!(PS_ATTRIBUTE; Attribute, Size, Value, ReturnLength);
    layout!(PS_ATTRIBUTE_LIST; TotalLength, Attributes);
    layout!(PS_CREATE_INFO; Size, State);
    layout!(FILE_BASIC_INFORMATION; CreationTime, LastAccessTime, LastWriteTime, ChangeTime, FileAttributes);
    layout!(FILE_NETWORK_OPEN_INFORMATION; CreationTime, LastAccessTime, LastWriteTime, ChangeTime, AllocationSize, EndOfFile, FileAttributes);
    layout!(MEMORY_BASIC_INFORMATION; BaseAddress, AllocationBase, AllocationProtect, RegionSize, State, Protect, Type);
    layout!(MEMORY_RANGE_ENTRY; VirtualAddress, NumberOfBytes);
    layout!(T2_SET_PARAMETERS; Version, Reserved, NoWakeTolerance);
    layout!(PORT_MESSAGE; DataLength, TotalLength, Type, DataInfoOffset, ClientId, MessageId, ClientViewSize);
    layout!(KEY_VALUE_ENTRY; ValueName, DataLength, DataOffset, Type);
    layout!(WNF_STATE_NAME; Data);
    layout!(WNF_TYPE_ID; TypeId);
    #[cfg(target_arch = "x86_64")]
    writeln!(
        header,
        "ASSERT(offsetof(X_MEMORY_BASIC_INFORMATION, PartitionId) == {}, \"PartitionId offset\");",
        core::mem::offset_of!(MEMORY_BASIC_INFORMATION, PartitionId)
    )
    .unwrap();
    let arch = if cfg!(target_arch = "x86_64") {
        "x64"
    } else {
        "x86"
    };
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("target/layout-contracts");
    std::fs::create_dir_all(&root).unwrap();
    std::fs::write(root.join(format!("layout-{arch}.h")), header).unwrap();
}
