//! C Bindings for SysWhispers3 Syscalls
//!
//! This crate provides C-compatible wrappers for all syscall functions.
//! The C header is auto-generated by build.rs during compilation.
//!
//! Usage from C/C++:
//! ```c
//! #include "syscalls.h"
//! 
//! SW3_NTSTATUS status = SW3NtAllocateVirtualMemory(...);
//! ```

#![allow(non_snake_case)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::too_many_arguments)]

// Re-export everything from syscalls for Rust usage
pub use syscalls::*;

// Include auto-generated C wrappers
include!(concat!(env!("OUT_DIR"), "/c_wrappers.rs"));
