//! Emit `syscalls.props` -- MSBuild import that wires MASM + the source files
//! into a .vcxproj with a single `<Import Project="syscalls.props"/>`.

pub const PROPS: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<!--
    X-Syscalls - MSBuild import
    In your .vcxproj add exactly one line:

        <Import Project="path\to\syscalls.props" />

    Include folder is added automatically ($(MSBuildThisFileDirectory)).
    Compiles syscalls.c on all platforms; picks x86 or x64 stubs by $(Platform).
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="ExtensionSettings">
    <Import Project="$(VCTargetsPath)\BuildCustomizations\masm.props"
            Condition="'$(Platform)'=='x64'" />
  </ImportGroup>

  <PropertyGroup>
    <IncludePath>$(MSBuildThisFileDirectory);$(IncludePath)</IncludePath>
  </PropertyGroup>

  <ItemGroup>
    <ClInclude Include="$(MSBuildThisFileDirectory)syscalls.h" />
    <ClCompile Include="$(MSBuildThisFileDirectory)syscalls.c" />
    <ClCompile Include="$(MSBuildThisFileDirectory)syscallsstubs.x86.c">
      <ExcludedFromBuild Condition="'$(Platform)'!='Win32'">true</ExcludedFromBuild>
    </ClCompile>
    <MASM Include="$(MSBuildThisFileDirectory)syscallsstubs.x64.asm"
          Condition="'$(Platform)'=='x64'" />
  </ItemGroup>

  <ImportGroup Label="ExtensionTargets">
    <Import Project="$(VCTargetsPath)\BuildCustomizations\masm.targets"
            Condition="'$(Platform)'=='x64'" />
  </ImportGroup>
</Project>
"#;

pub const README: &str = r#"# X-Syscalls -- standalone drop-in bundle

Auto-generated by `syscalls-standalone` from `syscalls-rust/lib.rs`.
Every symbol is prefixed with `X` (functions) or `X_` (types/constants),
so nothing collides with `<windows.h>`.

## Files

| File                        | Purpose                                             |
| --------------------------- | --------------------------------------------------- |
| `syscalls.h`                | Header: types, constants, function decls           |
| `syscalls.c`                | Runtime: PEB walk, hash table, atomic init         |
| `syscallsstubs.x64.asm`     | MASM PROC per syscall, x64 (jumper_randomized)     |
| `syscallsstubs.x86.c`       | MSVC `__declspec(naked)` stubs, x86 + WoW64 gate   |
| `syscalls.props`            | MSBuild import                                     |

## Integrate into a VS project (fastest way)

Add one line to your `.vcxproj`:

```xml
<Import Project="path\to\this\syscalls.props" />
```

That import:

  * adds this folder to `IncludePath`,
  * compiles `syscalls.c` on all platforms,
  * compiles `syscallsstubs.x86.c` only when `$(Platform)==Win32`,
  * assembles `syscallsstubs.x64.asm` only when `$(Platform)==x64`,
  * enables the MASM build customization on x64.

## Manual integration (no MSBuild import)

1. Add all four source files to your project.
2. Set `syscallsstubs.x86.c` to *Excluded From Build* on `x64` configs;
   set `syscallsstubs.x64.asm` to *Excluded From Build* on `Win32` configs.
3. Right-click the project -> **Build Dependencies** -> **Build Customizations**
   -> enable **masm** (needed for `.asm`).

## Usage

```c
#include "syscalls.h"

int main(void) {
    void*    base = 0;
    size_t   size = 0x1000;
    X_HANDLE hproc = X_NtCurrentProcess();

    X_NTSTATUS s = XNtAllocateVirtualMemory(
        hproc, &base, 0, &size,
        X_MEM_COMMIT | X_MEM_RESERVE,
        X_PAGE_READWRITE);

    if (X_NT_SUCCESS(s)) { /* base points at a fresh page */ }
    return 0;
}
```

## CRT-free notes

  * `syscalls.c` calls no CRT function -- no `strlen`, `memcpy`, `malloc`.
  * State lives in BSS (all zero on load); no CRT initializer runs.
  * Atomics use MSVC intrinsics (`_InterlockedCompareExchange`, `_mm_pause`)
    with inline prototypes, so `<intrin.h>` is never included.
  * The x64 stubs are pure MASM; the x86 stubs are `__declspec(naked)` + `__asm`.

## Regenerating

From the syscalls-rust workspace root:

```
cargo run -p syscalls-standalone -- --out <path\to\output\dir>
```

The output directory is created if missing; existing files are overwritten.
"#;
